//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10085591_CLDV6211_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string CarNo { get; set; }
        public string CarMake { get; set; }
        public string Model { get; set; }
        public string BodyType { get; set; }
        public int KilometersTravelled { get; set; }
        public int ServiceKilometers { get; set; }
        public string Availabile { get; set; }
        public int id { get; set; }
    }
}
