//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10085591_CLDV6211_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector
    {
        public string Inspector_no { get; set; }
        public string InspectorName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int id { get; set; }
    }
}
